jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: salih-senturk-client
server:
  port: 8081
spring:
  application:
    name: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/slhsntrk
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs